VRK-YTI/yti-datamodel-api

build.gradle

Downgrade jsonld library because it didn't work as expected in some cases

YTI-448 downgrade jsonld library

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/codes/Codes.java
src/main/java/fi/vm/yti/datamodel/api/model/SuomiCodeServer.java

Sometimes there are problems displaying codes in datamodel application if the indexing of codes has failed. If force parameter is provided, the timestamp check is ignored.

YTI-1675 Force update codes

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/model/Models.java
src/main/java/fi/vm/yti/datamodel/api/service/GraphManager.java
src/main/java/fi/vm/yti/datamodel/api/service/ImportManager.java
src/main/java/fi/vm/yti/datamodel/api/service/JenaClient.java
src/main/java/fi/vm/yti/datamodel/api/service/TerminologyManager.java

Changelog:
- Catch HTTP 404 exception and return null if it happens
- Why does it return 404 instead of null in the newer version anyways? Its hard to figure things out due to Jena having very little documentation
- Use try with resources for most connections to try and reduce more errors from happening
- Cleaned some logger commands as well

YTI-2114: catch 404s and return null instead of throwing error

---

src/main/java/fi/vm/yti/datamodel/api/index/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/index/model/ModelSearchRequest.java
src/test/java/fi/vm/yti/datamodel/api/index/EsUtils.java
src/test/java/fi/vm/yti/datamodel/api/index/ModelQueryFactoryTest.java
src/test/resources/es/modelrequest.json

Changelog:
- Added language filtering option: "language" parameter
- unit tests for ModelQueryFactory
- Cleaned some code smells
Example API request to `datamodel-api/api/v1/searchModels`
```json
{
"query": "",
"searchResources": true,
"sortLang": "fi",
"pageSize": 1000,
"pageFrom": 0,
"language": "fi" #new parameter
}
```

YTI-2271: support for language filtering in elasticsearch

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/model/ModelPositions.java

Deleting position graph before saving produces an error. Skipping this doesn't cause any duplication issues mentioned in the comment

skip deleting position graph before saving

---

src/main/java/fi/vm/yti/datamodel/api/index/SearchIndexManager.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/dto/CountDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/dto/CountSearchResponse.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/test/java/fi/vm/yti/datamodel/api/v2/elasticsearch/CountQueryFactoryTest.java
src/test/resources/es/models_count_request.json
src/test/resources/es/models_count_response.json

Changelog:
- Added endpoint for counts in `v2/frontend/counts`
- Slight note on the group count is that elastic search in terminology-api could return more information, but the datamodel-api elastic search only returns the identifier
- unit tests
- cleaned SearchIndexManager a bit
Example:
`http://localhost:9004/datamodel-api/api/v2/frontend/counts`
```json
{
"totalHitCount": 4,
"counts": {
"statuses": {
"DRAFT": 4
},
"languages": {
"en": 3,
"fi": 3,
"sv": 2
},
"groups": {
"P11": 1,
"P13": 2,
"P21": 1
},
"types": {
"library": 3,
"profile": 1
}
}
}
```

YTI-2309: Added counts for data models.

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/ElasticIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/main/resources/config/application.properties
src/test/java/fi/vm/yti/datamodel/api/integration/FusekiTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/service/ModelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/resources/es/models_count_request.json
src/test/resources/test_datamodel.ttl

- Fix sonarqube issues
- New tests for better coverage
- Fix old tests
- Remove ID from DatamodelDTO as it can be determined through prefix
- Modelmapper to service
- Fix prefixes
- 
- Add jacoco coverage reportingdatamodel-api/api/v2/model
- model api path is now `datamodel-api/api/v2/model`
- this is fixed by having a different slightly different context-path variable

YTI-2357 map to datamodeldto

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidDatamodel.java
src/main/resources/config/application.properties
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java

Changelog: 
- changed endpoint back to original as it caused v1 endpoints to not work correctly. 
- v1 = `datamodel-api/api/v1/<endpoint>`
- v2 = `datamodel-api/v2/<endpoint>`
- modelMapper for updating model.
- Same DataModelDTO but validation does not allow prefix and modeltype to be set
- end point for updating model.
- testing

YTI-2361: datamodel update endpoint

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/ElasticIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/IndexModel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/resources/model_v2_mapping.json
src/test/java/fi/vm/yti/datamodel/api/index/ModelQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/integration/FusekiTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/service/EndpointConnectionTest.java
src/test/java/fi/vm/yti/datamodel/api/service/ModelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/elasticsearch/ElasticIndexerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexControllerTest.java
src/test/resources/test_datamodel.ttl

Changelog:
- Add indexing controller with proper authorization requirements
- Create query for getting all datamodel graphs into a single model. 
- unit tests
- move prefixes to ModelConstants
- use Iow class as properties instead of defining every time

YTI-2363: elasticsearch indexing

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/resources/test_datamodel_v1.ttl

Changelog:
- Get languages for old models properly.
- ModelMapper will first try the statement as a RDF:List and then as separate statements
- Fix endpoints for JenaService
- Tests for old models (might be deleted in the future when old models are migrated)

YTI-2373 fix languages getmodel

---

src/main/java/fi/vm/yti/datamodel/api/security/AuthorizationManager.java
src/main/java/fi/vm/yti/datamodel/api/security/AuthorizationManagerImpl.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/ElasticIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/service/TestAuthorizationManagerImpl.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java

Changelog: 
- Add hasRightToModel to auth manager
- Use to check datamodel instead of datamodelDTO
- Fix tests to reflect this change (mainly just mocking the auth manager check)

YTI-2361: FIX check datamodel for orgs instead of datamodeldto

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java

Changelog:
- New ASK query for checking if graph exists in core
- Prefix validation
- Added length and pattern matching for external namespace
- Datamodel checks if current prefix is already in use and checks reserved prefixes
- Unit test for prefix checking

YTI-2375: Check prefix when creating

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/config/RestConfig.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/BaseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/GroupManagementOrganizationDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/GroupManagementUserDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/dto/IndexModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/dto/ModelSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/dto/ModelSearchResponse.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FakeableUserController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/OrganizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/FrontendService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/OrganizationMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java

Add missing features from legacy:
- freePrefix, users and fakeableUsers endpoints
- dto classes for Elastisearch response
Added simplified implementation for model search. Final implementation after Elasticsearch upgrade
Refactor (partly) model mapping. Moved some common methods to MapperUtils class. Add separate mapper class for Organizations.

YTI-2376 Add missing features

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexClass.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/resources/test_datamodel_with_class.ttl

- Add new property note for class. For now, stored in SKOS:note but it might change in the future
- Comment is stored to SKOS:editorialNote and it's not visible for unauthenticated users and not indexed in Opensearch either
- Add null check for getting list of properties as some of them might not exist, e.g. equivalentClass

YTI-2421 Class note and editorial note

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/NamespaceResolveController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ApiGenericError.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ResolvingException.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/NamespaceResolveControllerTest.java

Changelog:
- New Namespace Resolution controller
- unit tests
- New namespace resolving service
- Remove checking for core vocabulary for external namespaces (no ticket seperately for this)
- Add owl:Thing to subClassOf by default (YTI-2428)
- Better error messages for some exceptions
- Move some validation messages to ValidationConstants
- Fix ClassMapper unit tests

YTI-2408: Namespace resolution

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/resources/models/test_datamodel_with_minimal_class.ttl

Changelog:
-  changed comment to editorialNote
- Allow for null lists on DTO
- Update Class endpoint
-  Unit tests for updating and creating classes
- Updated validation rules for class
- editorial note -> length
- subclassof and equivalentclass allow null
- label -> null | empty check
- Searches are now GET request so parameters come in the form of parameters instead of a json body

YTI-2417: Added class update

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceType.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ResourceSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexResource.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchIndexerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json

Changelog:
- Map to index reource
- Class uses this one as well
- Refactored `searchInternalClasses` to `searchInternalResources`
- You can search all resources and limit with `resourceType`
- Reindexing takes in attributes and associations as wel now

YTI-2480 + YTI-2477: opensearch for attr and assoc

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

rename awsEnv to env because property with that name already exists in configuration

YTI-2371 rename aws env property

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/OpenSearchException.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ResourceSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java

Changelog:
- searching for internal resources can now be limited to a single datamodel
-  fromAddedNamespaces now a boolean and gets from limited datamodel
- Better exception handling for opensearch.
Note: There will be a separate PR for frontend for implementation of this in the UI

YTI-2493: limited datamodel searching

---

src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- new jena service functions for deletion
- new delete functions for deletion opensearch
- endpoints for model, class and resource for delete
- removed return value for index deletion
- better bulk response logging
Small bug fix:
You can add a resource relationship if the resource is in the same namespace as the class

YTI-2498: DELETE endpoint

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java

Existing data models don't have creator information. Add this check until user migration has been implemented

YTI-2500 add temporary null check for creator user id

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/PositionDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java
src/test/resources/models/test_datamodel_visualization.ttl

- DTO classes for visualization data
- Visualization data mapper, for now only mapping for classes
- parent classes (based on subClassOf property) are mapped with prefix e.g. test:ClassName if in external model. If the parent class is in the same model, only class identifier is added to the list
- Position mapping will be implemented later

YTI-2438 map visualization data for classes

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimpleResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/SparqlUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/resources/models/test_resource_query_model.ttl

Changelog:
- Added simpleResource information to class GET endpoint
- moved some functions to SparqlUtils
- Fixed some validation for update allowing them to be null New map from construct
- New construct query for domain and range
- all linked resources in attributes and associations are now saved in fuseki as uris instead of plaintext
```json
"attribute": [
{
"uri": "http://uri.suomi.fi/datamodel/ns/example#attribute4",
"label": {
"fi": "example"
},
"identifier": "attribute4",
"modelId": "example"
},
],
"association": []
```

YTI-2541: get class resources endpoint

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ConceptDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/TerminologyNodeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/TerminologyMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexResource.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/TerminologyMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/TerminologyServiceTest.java
src/test/resources/concept_response.json
src/test/resources/terminology_with_concept.ttl

- Concepts are resolved from sanastot.suomi.fi and stored to Fuseki, in the same graph as related terminology
- Add concept uri to Opensearch index
- Add mapper consumer to terminology service which enriches concept data for UI

YTI-2506 Add concept to resources

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/resources/models/test_datamodel_visualization.ttl
src/test/resources/models/test_datamodel_with_minimal_resources.ttl
src/test/resources/models/test_datamodel_with_resources.ttl
src/test/resources/test_datamodel.ttl

Changelog:
- All linked resources in datamodels/classes/attributes/associations are now stores as uris in fuseki
- Remove prefix when removing namespaces
- Add status validation for when creating datamodel

YTI-2547: linked resources to uris

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveController.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveControllerTest.java

- Moved data serialization from DatamodelController to ExportController 
- Hide some data from unauthenticated users (skos:editorialNote)
- Created controller for URI resolving (ResolveController)
- Determine if either single resource or the whole model is requested and redirect request forward per accept header. Redirect to site only if accept header is `text/html`, otherwise redirect to ExportController to get serialized data

YTI-2497 resolve URIs and redirect to resource

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

Use terminology uri with suffix because otherwise searching terminologies by uri doesn't work

YTI-2506 use terminology uri with suffix

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ExternalClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ExternalResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ResourceSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexResource.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/MapperTestUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/resources/external_class.ttl
src/test/resources/models/test_datamodel_profile_with_resources.ttl
src/test/resources/properties_result.ttl

- While saving new node shape, create also placeholder property shapes based on selection in creation modal
- New endpoints for getting external class and searching all node shapes based on specific class (sh:targetClass)
- Refactoring: checking resource type, separate tests for class and node shape
- Some fixes to indexing: bulk indexing in batches, add resource type to query in index initialization

YTI-2591 new nodeshape mapping and saving

---

src/main/java/fi/vm/yti/datamodel/api/config/RestConfig.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/CodeListDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/CodeListMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/TerminologyMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/CodeListService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/CodeListMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/TerminologyMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/CodeListServiceTest.java
src/test/resources/codelist.ttl
src/test/resources/codelist_response.json
src/test/resources/test_datamodel_library.ttl
src/test/resources/test_datamodel_profile.ttl

Changelog:
- Codelist support for application profile
- Mapper
- Service
- DTO
- Simplified terminology mapping and service, there is no need to get the old model for a terminology if we are replacing all of its contents anyway, better to just put a new one in its place
- rename uriresolveclient
- Unit tests

Feature yti 2606 codelist support

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

Endpoint for toggling `sh:deactivated` property
```
PUT /datamodel-api/v2/class/toggleDeactivate/{prefix}?propertyUri=http://uri.suomi.fi/datamodel/ns/test%23SomeProperty
```

YTI-2591 Add deactivation endpoint

---

src/main/java/fi/vm/yti/datamodel/api/StartUpListener.java
src/main/java/fi/vm/yti/datamodel/api/migration/FusekiSchemaVersionAccessor.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V1_Initial.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V2_Separator.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java

Changelog:
- Added migration support
- New migration task for changing separator for resources
- This migration task is done under the assumption that the data in the database is using the new v2 models
- V1 task was left open for creating a task to update production data to the new v2 models, so it may not be run in test and dev environments where task V2 was already run
NOTE: Before installation #133  should be merged as well

Feature yti 2602 separator migration task

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/CountQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json

Changelog:
- Increased datamodel limit on internal queries to 10000 (elastic search default upper limit)
- Refactored CountQueryFactory to static
- Cleaned up other query factories a bit
- Added targetClass query  parameter to unit test

YTI-2569: Resource query not listing all resources

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Removed some null checks since no matter what the collections will be initialized

YTI-2606: Fix validator to not check for library if modeltype is null

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/resources/property_shapes_result.ttl

Endpoints for adding and removing property shapes (update node shape's `SH.property`)
```
PUT /datamodel-api/v2/class/profile/{prefix}/{identifier}/add-property?uri=http://uri.suomi.fi/datamodel/ns/foo/some-property
DELETE /datamodel-api/v2/class/profile/{prefix}/{identifier}/delete-property?uri=http://uri.suomi.fi/datamodel/ns/foo/some-property
```
Endpoint for fetching recursively properties from sh:node reference. Data fetched from OpenSearch.
```
GET /datamodel-api/nodeshape/properties?nodeURI=http://uri.suomi.fi/datamodel/ns/foo/some-class
```
Changed reference property shape handling that no placeholder resource is created, only reference with `SH.property`. Also created sparql query for fetching resources from Fuseki based on `SH.property` values
Other refactorings and fixes
- …

YTI-2567 Single property missing features

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/ConceptInfo.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/DatamodelInfo.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexResourceInfo.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/resources/all_concepts.ttl

In some cases data model and concept data is needed to display search results. Add new endpoint, which returns enriched data. Search functionalities are not changed.
Fix also checking note's length (allow 5000 characters)

YTI-2578 map search modal data

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/DatamodelInfo.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json
src/test/resources/external_resources.ttl

- create new index for external resources and init it while application starts
- external resources are indexed after resolving
- include this index to search if there are external namespaces added to the query
- index resource mapping logic from jena model -> IndexResource object
- refactor isDefinedBy query

YTI-2609 Index external classes 

---

src/main/java/fi/vm/yti/datamodel/api/Application.java
src/main/java/fi/vm/yti/datamodel/api/StartUpListener.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexControllerTest.java

Changelog:
- Added resolving of external namespaces
- Refactored namespace resolver to work with more content types
- Added JVM setting to Application.java to allow for more redirects using the HttpClient
- This was blocking some namespaces from resolving due to having more than the default 5
- Resource mapper can now check for inverseOf for type and can check literal range if it is using unionOf
- Indexer does not index external resources on startup anymore (so that external resources are not indexed twice)
- More options on reindexing through API

YTI-2628: resolve external namespaces

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidDatamodel.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

- Changed paths /ontology -> /library as also application profiles might be ontologies
- Add separate endpoint for creating and updating application profile and library. Thus, we can add validation based on model type. ModelType is no longer provided in the payload
- Add mapping tests for both library and profile

YTI-2425 Data model endpoints for profile and library, validation fixes

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V3_ImportsRequires.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/resources/test_datamodel_library.ttl
src/test/resources/test_datamodel_profile.ttl

Changelog:
- Refactored model mapper, sonarqube fixes and made code more generic in some places
- Changed model mapper to map linked data properly.
- This includes codelists and terminology. 
-  Codelist and Terminology -> dcterms:requires
- add library to library -> owl:imports
- add profile to library -> dcterms:requires
- add library to profile -> dcterms:requires
- add profileto profile -> owl:imports
- Migration for this change 
- unit tests

YTI-2622: Moved datamodel linked data to right properties

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ResourceSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/attributeListRequest.json
src/test/resources/es/classRequest.json

- Created sparql query for getting all external resources from sh:property
- Modify opensearch query that it matches resources defined in this model or external resources got from mentioned sparql query. e.g.
```
{
"query": {
"bool": {
"must": [
{
"bool": {
"should": [
{
"terms": {
"isDefinedBy": [
"http://uri.suomi.fi/datamodel/ns/test"
]
}
},
{
"terms": {
"id": ["http://uri.suomi.fi/datamodel/ns/other/some-resource"]
}
}
]
}
},
{
"terms": {
"resourceType": [
"ATTRIBUTE"
]
}
}
]
}
}
}
```
Also fixed `/v2/class/nodeshapes` endpoint to return extended information of data model and terminology (related to YTI-2591)

YTI-2624 include additional resources to search

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- New endpoint for making copy of propertyshape
- Mapper copies all properties of old one and sets metadata for new model
- unit tests

YTI-2668: New endpoint for copying propertyshape

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/NodeShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java

Handle changing nodeshape's sh:node and sh:targetClass references
- When sh:node reference changes, properties based on new reference, are added to the node shape. Properties of previous sh:node reference are not removed (for now)
- When creating new property shapes based on targetClass, check if there is already property shape with sh:path reference to the same attribute/association. If that kind of property shape is found, add only reference to existing one, otherwise create new resource as before.
- Also while creating property shapes for targetClass, add check that the identifier is not in use in current model. If it is in use, add suffix e.g. some-attribute-1

YTI-2636 change nodeshape references

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/repository/BaseRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/repository/ImportsRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java

- Add endpoint for fetching resolved namespaces
Refactor JenaService (in this PR only form imports dataset)
- Create on repository class per dataset in Fuseki, e.g. ImportsRepository, CoreRepository etc.
- Create BaseRepository with basic actions for saving and fetching data from Fuseki
- Future goal: move specific methods, e.g. getServiceCategories, from JenaService to some more appropriate service class. Create repository classes for all other datasets.

YTI-2627 fetch resolved namespaces

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FakeableUserController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- Creating new models and resources are now POST and return 201 with the URI
- Modifying is PUT and return 204
- All camelCase endpoints to kebab-case
- Reordered some endpoint text to make more sense
- Rename Datamodel to DatamodelController
- Free prefix are now exists and they are completely reversed now
- Changed some property names so they are uniform
- Fixed all unit tests

YTI-2695: restful api fixes

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PositionDataDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationAssociationDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationHiddenNodeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationItemDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationResultDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java
src/test/resources/positions.ttl

- New endpoint for saving coordinates PUT /datamodel-api/v2/visualization/{prefix}/positions. Old positions are removed if exists
- Changed response type of getting visualization data: separated visible and hidden nodes
- Map positions to VisualizationClass objects
- Determine path between nodes and create hidden nodes (with position, identifier and references) as needed
- Add validation rule for classes and nodeshapes, that identifier cannot start with `corner-`
Saving positions for two nodes (class-1 and class-2) connected via two hidden nodes (corner-1 and corner-2)
```
[
{
"identifier": "class-1",
"x": 0.0,
"y": 10.0,
"referenceTargets": [
"corner-1"
]
},
{
"identifier": "class-2",
"x": 10.0,
"y": 20.0,
"referenceTargets": []
},
{
"identifier": "corner-1",
"x": 40.0,
"y": 40.0, …
```

YTI-2693 visualization coordinates

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/NodeShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoBaseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/UriDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexBase.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/resources/models/test_datamodel_library_with_resources.ttl
src/test/resources/models/test_datamodel_profile_with_resources.ttl

- add curie beside to uri in response objects (ResourceBaseInfoDTO), also for index resource
- add utility function for setting model prefixes (moved from ExportController)
- change uri references (e.g. domain, subclassOf, equivalentProperties) to UriDTO objects containing both uri and curie. Determine curie from model's prefixes or straight from uri if prefix not added to the model.
- fixed validation for subclasses and equivalentClasses

YTI-2673 add curie identifiers

---

src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchUtil.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/resources/es/classRequest.json

Changelog:
- Show what index opensearch payload was from
- Don't add limitToDataModel if it is not the right type
- Remove old sh:node properties if changing and add new ones
- Remove old sh;node properties if removing

YTI-2680: Remove old sh:node properties

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java

Changes in this PR:
- Prefix min length changed from 3 to 2
- Regex updated to accept prefixes of length 2

Prefix min changed from 3 to 2

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V5_VersionStatus.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Status.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/CountRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ModelSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/CountQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ModelQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/attributeListRequest.json
src/test/resources/es/classRequest.json
src/test/resources/es/modelrequest.json
src/test/resources/es/models_count_request.json

Changelog:
- **Status**
- Removed INVALID
- Removed INCOMPLETE
- DRAFT --> SUGGESTION
- INCOMPLETE --> DRAFT
- **Migrate**
- NOTE: INVALID --> RETIRED just in case some use this
- **Opeansearch**
-  DRAFT now hidden by default
-  SUGGESTED shown by default with VALID
- Fix should query a bit (caused DRAFT not to show if superuser) now if superuser no should query is shown
- **Mapping**
- Creation DRAFT is default now for datamodel
- Creation does not allow to use custom status anymore
- Fixed some unit tests involving Status

YTI-3196: Status migration and change

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

The following calls will remove the value if it's missing from the payload:
* updateStringProperty
* updateLiteral
* updateUriProperty
This is done by always calling removeAll, and then checking if value should be added. e.g.:
```java
resource.removeAll(property);
if (value != null) {
resource.addLiteral(property, value);
}
```
Added validation for missing sh:path.
Fixed tests for invalid attribute restrictions and association restrictions. Previously they all failed for the same reason, instead of for the things that were actually being tested.
* `checkIfResourceIsOneOfTypes` is mocked, so the tests don't fail by default
* The test providers will also provide `String[] expectedResult`, which is a list of all the validation errors that the particular test case should cause

allow deleting properties by omitting the value in update

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexModel.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/SemVer.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/SparqlUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/utils/SemVerTest.java
src/test/resources/test_datamodel_library.ttl

Changelog:
**Controller**
- New endpoint  `v2/model/{prefix}/release`
**Indexing**
- New fields for datamodel
- Id now has version number attached so that they can still be unique
- Datamodel index construct query rewritten. It can now handle datamodels with same uri from different named graphs
**Semantic versioning**
- New SemVer class for comparing Semantic versions
- Is  able to differentiate between preReleases as well
**ModelMapper**
- Adding version release specific properties
- Not adding non-mvp properties yet
**DatamodelService**
- Function for creating release
- Check status for only allowing VALID AND SUGGESTED
- Check that string matches SemVer regex
- Check that new version is bigger than older one
- Map version properties to new release
- Map new release version uri to …

YTI-3194: Datamodel version control

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/resources/models/test_datamodel_library_with_resources.ttl

When handling class's owl:equivalentClass resource, check that the object is not anonymous

YTI-3191 fix handling owl:equivalentClass

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceIdentifierValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidResourceIdentifier.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java

The identifier is checked for valid format using regex.
Previously the free identifier check would throw Internal Server Error if the identifier had spaces in it (e.g. "asd "):
```json
{
"timestamp": "2023-10-03T07:50:53.425+00:00",
"status": 500,
"error": "Internal Server Error",
"path": "/datamodel-api/v2/class/urhotest1/asd%20/exists"
}
```
With spaces, the generated sparql query would be invalid:
```sparql
ASK
WHERE
{ GRAPH <http://uri.suomi.fi/datamodel/ns/urhotest1>
{ <http://uri.suomi.fi/datamodel/ns/urhotest1/asd  >
?p  ?o}}
```
This PR adds a new validator to every endpoint where the identifier is used. After this, we get a Bad Request with validation error details:
```json
{
"status": "BAD_REQUEST",
"timestamp": "03-10-2023 11:00:07",
"message": "Object validation failed", …
```

Add validator for resource identifiers

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexResource.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json
src/test/resources/es/classesByVersion.json
src/test/resources/models/test_datamodel_library_with_resources.ttl

Add internal namespcaes to model
- fetch referenced model's prefix without version
- fix displaying prefix in visualization data (strip version)
Logic changes in resource search
- If no data models found by searching with e.g. groups, return empty set
- Split namespaces to internal and external. Internal namespaces are searched by `versionIRI` (added also to indexed resource), external resources are searched by `isDefinedBy`. Version parameter is affected only to current model (limitToDataModel)
Example: Querying classes for draft model `test` with added internal namespace `ext` (version 1.0.0) and external namespace `owl`
```
{
"from": 0,
"query": {
"bool": {
"must": [
{ "terms": { "status": ["VALID", "SUGGESTED"] } },
{
"bool": {
"minimum_should_match": "1",
"should": [
{
"bool": { …
```

YTI-3416 link internal namespaces with version

---

src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimplePropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimpleResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java
src/test/resources/models/test_resource_query_model.ttl
src/test/resources/properties_result.ttl
src/test/resources/test_datamodel_profile.ttl

Changes for fetching and adding resources with version information
- modify findResources query to limit only specified graphs (the namespaces added to the model)
- add versionIRI to the search results
- map version info to SimpleResourceDTO
- modify checking if resource is required type for validation
Other changes
- remove unused endpoint /datamodel-api/v2/class/nodeshape/properties
- add some utility methods for handling URIs with version

Yti 3418 find resources with version checks

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/resources/test_datamodel_library.ttl

While saving references to other data modes (e.g. adding subClassOf), add namespace to the data model's metadata (owl:imports or dcterms:requires) if it's not already present.

YTI-3406 automatically add reference namespaces

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java

If identifier contains only numbers, resources getLocalname method doesn't work (returns empty string)

YTI-3328 check that identifier starts with letter

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java

Changelog:
- Keyword field on dynamic properties are now normalized into lowercase since they are only used for sorting
- Remove unneccesary path for Property import

YTI-3594: case insensitive sorting

---

src/main/java/fi/vm/yti/datamodel/api/v2/repository/BaseRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceIdentifierValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java

- case-insensitive check if resource exists, e.g. if resource with identifier 'test' exists, cannot create resource with identifier 'Test'
- create separate methods for prefix and identifier validation

YTI-3563 indentifier and prefix validation

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/UriResolveService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/UriResolveServiceTest.java

Extract version from uri if present and add required version parameter to generated url
Example
`http://uri.suomi.fi/datamodel/ns/testmodel/1.0.0` redirects to `/model/testmodel?ver=1.0.0` or `/datamodel-api/v2/export/testmodel?version=1.0.0` if accept header is something else than text/html

YTI-3571 support version in uri resolving

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/visualization/VisualizationClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java

Remove unnecessary prefixes on export
Remove setting of prefixes everywhere, these prefixes are not really used by code so they are only necessary when exporting the triplets.

YTI-3253: Remove unnecessary prefixes for export

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ResourceSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java

Changelog:
- Remove if check on includedNamespacesQuery since restrictedDatamodels will never be null
- Add include draft from to resource query 
- this is so that in case someone uses all datamodels filter and still wants to see the currently edited datamodel

YTI-3610: Include draft from from models query added

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/AuditService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchIndexerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolverTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java

Changelog:
- Remove unneccessary logging on frontend controller
- Exception handler for AuthorizationException
- Removes unneccessary error message when someone does not have permissions
- Added audit logging 
Example log:
`2023-11-24T12:26:58.831+02:00  INFO 65518 --- [nio-9004-exec-8] f.v.y.d.api.v2.service.AuditService      : VISUALIZATION SAVE: <http://uri.suomi.fi/datamodel/ns/all_models>, User[email=admin@localhost, id=4ce70937-6fa4-49af-a229-b5f10328adb8]
`

YTI-3223: Added audit logging to user callable functions

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V13_StatusToUri.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/CodeListMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/TerminologyMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/CodeListMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java
src/test/resources/codelist.ttl
src/test/resources/migration/old-identifiers-version.ttl
src/test/resources/migration/old-identifiers.ttl
src/test/resources/models/test_datamodel_library_version.ttl
src/test/resources/models/test_datamodel_library_visualization.ttl
src/test/resources/models/test_datamodel_library_with_resources.ttl
src/test/resources/models/test_datamodel_prior_versions.ttl
src/test/resources/models/test_datamodel_profile_with_resources.ttl
src/test/resources/models/test_datamodel_with_minimal_resources.ttl
src/test/resources/properties_result.ttl
src/test/resources/property_shapes_result.ttl
src/test/resources/terminology_with_concept.ttl
src/test/resources/test_datamodel_internal_reference.ttl
src/test/resources/test_datamodel_library.ttl
src/test/resources/test_datamodel_profile.ttl

Changelog:
- Use uri instead of string for publication status

YTI-3720: publicationStatus to use uri in codelists

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V14_IowObjectSuomiMeta.java

Changelog:
- Forgot to migrate objects as well to Suomi-meta, now application profiles should show correctly

YTI-3680: migrate iow on objects as well to suomi-meta

---

src/main/java/fi/vm/yti/datamodel/api/config/RestConfig.java
src/main/java/fi/vm/yti/datamodel/api/migration/DataMigrationController.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMapper.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexBase.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/migration/DataMigrationTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/migration/V1DataMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/TerminologyServiceTest.java

- Replace associations with label "yläluokka" with rdfs:subClassOf reference
- Determine restriction's type based on sh:path if not defined in restriction resource
- Rename resources with trailing underscore, if one already exists with capital initial letter
- Changes for uri.suomi.fi -> iri.suomi.fi
- Add some spacing for nodes in visualization (multiple coordinate values with 1.2)
- Create version 1.0.0 of migrated models and change references to published version in other models
- Fetch class resources from Opensearch, because spraql query is very inefficient if there are more than 20 resources
- Add resource's uri to index. This is needed when fetching multiple resources from Opensearch as described above.
- Skip resolving terminology when creating or modifying data model if it's …

YTI-3688 migration new features and performance improvements

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelSearchResultDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchClientWrapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ModelSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/SearchResponseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexBase.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/resources/es/modelrequest.json
src/test/resources/es/models_count_request.json

Search results will now also find models if their resources match the keyword. This is done by performing an additional search, and combining the search results.
* search-models will return `ModelSearchResultDTO`, which adds matching resources to the search result in addition to the model data
* matching keywords will be highlighted in the search result
* `IndexBase` base class now contains `highlights` property
* opensearch queries have been rearranged (`must`/`should`), hopefully for more correct behaviour
Cut down example of the result:
`/v2/frontend/search-models?pageSize=50&searchResources=true&sortLang=fi&status=VALID&query=test`
```json
{
"responseObjects": [
{
"id": "https://iri.suomi.fi/model/test/1.0.0/",
"uri": "https://iri.suomi.fi/model/test/1.0.0/",
"label": {
"fi": "Test …
```

search models by resources

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java

- When mapping application profile resources, use resource uri with version
- When mapping library resources, check if external resource is part of Interoperability platform

YTI-3752 fixes for handling external resources

---

src/main/java/fi/vm/yti/datamodel/api/migration/DataMigrationController.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMapper.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/migration/DataMigrationTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/migration/V1DataMapperTest.java
src/test/resources/migration/fi-dcatap.ttl

- migration script for profiles
- tweak validations (type of sh:path and allow reserved prefixes when linkin external namespace)
- add prefixes of the external namespaces to model's prefix map
- return errors in the response after migration finished
- add foaf to resolved namespaces
- update references from draft version to published one when creating new version

YTI-3812 Application profile migration

---

src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/resources/es/attributeListRequest.json
src/test/resources/es/classRequest.json
src/test/resources/es/classesByVersion.json

- Add new resolvable namespaces
- Simplify the query which fetches resources for indexing, as it's very slow with larger datasets
- Use only application/ld+json accept header when resolving uncefact namespace (works only with one accept header)
- Add curie for external resources in index
- Use namespace field when searching external resources from OpenSearch, because isDefinedBy might refer to different namespace or might miss resource separator

YTI-3830 External namespaces changes

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/visualization/VisualizationHiddenNodeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java

Add origin for hidden nodes to make it easier to set association / parent relation highlights in the UI. For association references the origin is association id, for parent relations origin is source class id.

YTI-3823 add origin for hidden nodes

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceReferenceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java
src/test/resources/references-result.ttl

Find all references to particular resource. In the simplest case, the reference is added as an object to the triple where the subject is the resource uri (e.g. <http://subject> <rdfs:subClassOf> <http://reference>). In more complex one,  the reference is an object of a blank node. The structure looks like this
```
test:test-class  rdf:type    owl:Class ;
rdfs:isDefinedBy         test: ;
rdfs:label               "Testiluokka"@fi ;
owl:equivalentClass      [ rdf:type            owl:Class ;
owl:intersectionOf  (
[ rdf:type            owl:Restriction ;
owl:onProperty      test:test-association ;
owl:someValuesFrom  test:test-target
]
)
]
```
With sparql we can find the subject (test:test-class) for an object (test:test-target):
```
SELECT ?classSubj ?label WHERE { 
GRAPH ?graph {
?subject …
```

YTI-2554 Resource's references

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java

For performance, fetch model's external resources from Opensearch instead of Fuseki. Fetch single class's resources at once, not one by one.

YTI-3842 visualization performance

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json

Add new search condition if there are draft models in internal namespaces:
...
OR {
isDefinedBy = ["draft-1", "draft-2"]
AND
not exists (fromVersion)
}
...
See frontend changes: https://github.com/VRK-YTI/yti-ui/pull/695

YTI-3874 include results from draft models

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java

Created a new endpoint `GET /model/prefix/validate`. For now, only validation rule checks that application profile has no resources without reference to core data model. Remove validation from sh:path.
Other changes
- Fix search resource query when modelType = profile (filter out all libraries from linked data models)
- Remove `@ValidResourcePrefix` annotation from get class endpoint

YTI-3922 default references and validation before release 

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java
src/test/resources/es/classRequest.json
src/test/resources/models/test_datamodel_profile_with_resources.ttl

Split mapping node shape properties: 
- properties in the same model, get them from model already fetched
- external properties, fetched from OpenSearch
- setting property restrictions (inherited from sh:node reference / is property deactivated)
- Create a local copy (missing source property shape version)
- Handle linked draft models
- Better unit tests for creating and getting class / node shape
- Fix sonar errors and remove unused code / method parameters

YTI-3849, YTI-3932 Fix node shape references

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/NodeShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/NodeShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/properties/HTTP.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

- Add new property API path for node shape, stored to the property `http://www.w3.org/2011/http#absolutePath` as in old application
- Created new property class HTTP because the property is not available in Jena

YTI-3940 Add api path for node shapes

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelURI.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java

If the version of dependency model is changed, all references (e.g. subClassOf) to the resources of that model will be updated to new version. Removing dependency model with any references will cause a validation error.

YTI-3903 update linked models

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/OpenAPIBuilder.java
src/test/resources/open-api-data.ttl
src/test/resources/open-api-expected.json

Add `$ref` property for associations with type = object. In this case type and all other properties are redundant because they are filtered out by pretty print.
For example
```
"property-1": {
"title": "Test title",
"type": "object",
"$ref": "#/components/schemas/class-1"
}
```
After pretty print
```
"property-1": {
"$ref": "#/components/schemas/class-1"
}
```

YTI-3958 set missing $ref property for associations

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java

In following scenario:
When determining path from CLASS-2 to CLASS-1, we start checking which nodes have CLASS-1 as their reference target. The result is CLASS-2 and C1 (hidden node) and in some cases we might get the wrong node (in this case hidden node C1).
Fixed this by checking hidden nodes' path and comparing the staring point to the source node identifier.

YTI-3999 Fix setting hidden node's origin

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/ReleaseValidationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/release/ReferencesExistsValidator.java

- skip checking graph references (owl:imports and dcterms:requires)
- add exception handling so release is possible to create despite unhandled exception in the validation

YTI-3939 Fixes to checking if resource exists

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaBuilder.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaTest.java
src/test/resources/json-schema-data.ttl
src/test/resources/json-schema-expected.json
src/test/resources/open-api-data.ttl

Added json schema export using the org.everit.json.schema library.
This library doesn't support the latest draft, and is in maintenance mode, so it might not be the final solution.

add simple json schema support

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java

Allow removing draft data models if:
- there are no published versions (draft version)
- there are no references to the model (owl:imports / dcterms:requires)
Normal user can remove only draft version if conditions above are true. Super user can remove also published versions if there are no references to them. When removing versioned models, `owl:priorVersion` information is updated.
Other bug fix: fix checking if graph exists (add missing trailing slash)

YTI-4042 Remove datamodels

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java

If there are more than one association with the same id (uri) and target, it will cause an issue when it is removed. This should not be any issue in the new application but migrated data may contain this kind of data.

YTI-4030 Fix orphan blank nodes

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/UriResolveService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/UriResolveServiceTest.java

Resolve IRI based on model id and resource id. If user has permissions to model, return draft (e.g. https://iri.suomi.fi/model/model-id/), otherwise return latest version (e.g. https://iri.suomi.fi/model/model-id/1.0.0/)

YTI-4074 v1 redirects

---

src/main/java/fi/vm/yti/datamodel/api/StartUpListener.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceResolver.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java

Add https://gs1.org/voc/ namespace. Because namespace is not resolvable, create new map containing resolvable URL for each not resolvable namespace. 
Fix startup initialization by moving namespace resolving after Opensearch indexes creation.

YTI-4106 Add new namespace 

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V15_VisualizationAddOrigin.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/visualization/PositionDataDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/properties/SuomiMeta.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java
src/test/resources/positions.ttl

Store origin of the line to each corner node. When determining the path from source node to target node, check that each corner node has correct origin and ending point of the line matches the source node.
Created a migration script for modifying old data to new format.
Old data with only information of the corner id
```
test:person
dcterms:identifier      "person" ;
suomi-meta:posX                "1.0"^^xsd:double ;
suomi-meta:posY                "2.0"^^xsd:double ;
suomi-meta:referenceTarget     "corner-1" .
test:address
dcterms:identifier      "address" ;
suomi-meta:posX                "10.0"^^xsd:double;
suomi-meta:posY                "20.0"^^xsd:double .
test:corner-1
dcterms:identifier      "corner-1" ;
suomi-meta:posX                "6.0"^^xsd:double ;
suomi-meta:posY …
```

YTI-4025 Add origin to visualization data

---

src/main/java/fi/vm/yti/datamodel/api/migration/DataMigrationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/AddCodeListPayloadDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimpleResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java

- New endpoints for adding and removing code lists to/from library class' attributes
- If node shape is created based on library class (sh:targetClass), possible code lists will be added automatically to node shape's property shapes
Code list reference is saved to owl:Restriction resource, e.g.
```
test:class-1  rdf:type                owl:Class ;
rdfs:isDefinedBy              test: ;
rdfs:label                    "testiluokka"@fi ;
dcterms:identifier            "class-1"^^xsd:NCName ;
owl:equivalentClass           [ rdf:type            owl:Class ;
owl:intersectionOf  ( 
[ rdf:type             owl:Restriction ;
owl:onProperty       test:attr-1 ;
owl:someValuesFrom   xsd:anyURI ;
suomi-meta:codeList  "http://uri.suomi.fi/codelist/sbr-fi-code-lists/AI"
]
)
] ;
suomi-meta:publicationStatus …
```

YTI-4137 library code lists

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/UriResolveService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/UriResolveServiceTest.java

- Create separate endpoint for getting draft (`GET /model/{prefix}/draft`) and published (`GET /model/{prefix}?version={version}`) data model. If not version parameter specified, return latest version.
- Redirect iri.suomi.fi addresses to latest published version if no version specified

YTI-4151 Redirect to latest version

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java

Combine validations for identifier length and allowed characters. Allow max 120 characters as resource's (class, attribute, association), data model's prefix max length is 32 as before.

YTI-4145 Resource identifier validation

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V16_MigrateLibraryCodeLists.java

Fetches code list references from models defined in application properties (`datamodel.v1.migration.librariesWithCodeLists`). Migration script adds `dcam:memberOf` property value to class' attribute restriction with the same `sh:path` value.
**Simplified example**
Old data
```
raktkk:KalusteenTyyppi
rdf:type            rdfs:Class ;
rdfs:isDefinedBy    <http://uri.suomi.fi/datamodel/ns/raktkk> ;
sh:name             "Kalusteen tyyppi"@fi ;
sh:property         <urn:uuid:b1707901-45a2-4afd-80a3-f3b54ecd8955> .
<urn:uuid:b1707901-45a2-4afd-80a3-f3b54ecd8955>
rdf:type         sh:PropertyShape ;
dcam:memberOf    <http://uri.suomi.fi/codelist/rakrek/raktkk_furniture_4_0_2_1> ;
sh:name          "Kalusteen laji"@fi ;
sh:path          raktkk:kalusteenLaji .
```
Migrated result
``` …
```

YTI-4150 migration script for library code list references

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ModelQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/attributeListRequest.json
src/test/resources/es/classRequest.json
src/test/resources/es/classesByVersion.json
src/test/resources/es/modelrequest.json

Determine starting index (from) in the backend. Paging parameter from UI (pageFrom) represents the page number, so the starting index is calculated `(pageFrom - 1) * pageSize`

YTI-4111 Move pagination logic to backend

---

src/main/java/fi/vm/yti/datamodel/api/v2/repository/BaseRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java

Add graph to delete query to prevent deleting resources from other graphs. Query looks like this:
```
DELETE {
GRAPH <https://iri.suomi.fi/model/test/> {
?s ?p ?o .
}
}
WHERE
{ GRAPH <https://iri.suomi.fi/model/test/>
{ ?s  ?p  ?o
FILTER ( ( ?s = <https://iri.suomi.fi/model/test/class-1> ) || ( ?o = <https://iri.suomi.fi/model/test/class-1> ) )
}
}
```
Old query
```
DELETE {
GRAPH ?g {
?s ?p ?o .
}
}
...
```

YTI-4234 add graph to delete query

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/VersionedModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java

Limit for documentation should be 50k characters. While saving versioned data model, the limit was only 5k characters.  Created common method for checking documentation to BaseValidator.

YTI-4241 fix validation for versioned model's documentation

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaBuilder.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaTest.java
src/test/resources/json-schema-data.ttl
src/test/resources/json-schema-expected.json

Add more restrictions to JSON schema
- min-/maxLength (string)
- pattern (string)
- min-/maxInclusive (number)
- min-/maxExclusive (number)
- const, if hasValue is provided
- enum, if allowedValues is provided
- defaultValue (all)
ArraySchema: Property is handled as an array if minCount > 1 or maxCount is empty or > 1.
MapperUtils fix: check if property value is literal, `toString` method returns value with type e.g. `"1"^^xsd:long`

YTI-4195 json schema improvements

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/resources/test_datamodel_profile.ttl

When selecting properties from node shape's target class, fetch them from OpenSearch rather than Fuseki. Sparql query used for fetching resources is quite heavy especially if several properties are selected.
Fixed also checking existing sh:path references. In the scenario where we have a property shape with a path reference 
```
<https://iri.suomi.fi/model/test-profile/attribute-1>
a                   sh:PropertyShape ;
sh:path            <https://iri.suomi.fi/model/test-library/attribute-1> .
```
Next we create a new node shape and select resource `https://iri.suomi.fi/model/test-library/attribute-1` as a path reference in the dialog after selecting target class. After the node shape is created, an existing property shape (`https://iri.suomi.fi/model/test-profile/attribute-1`) is added …

YTI-4233 Fetch target class properties from OpenSearch

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V17_TerminologyIRIs.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java

Use new iri.suomi.fi format in terminology and concept URIs. Craeted migration task and changed validation rules.

YTI-4260 Terminology URIs

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/test/resources/es/classRequest.json
src/test/resources/es/modelrequest.json

- Use `and` operator with multiple words, e.g. query string "test search" -> `*test* AND *search*`.
- Removed sorting if query string is specified

YTI-4278 use and operator with separate words

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

If concept list is empty, return empty model. Otherwise query will get too heavy (=returns all concepts)

YTI-4260 check concept list

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/test/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java

- Create draft version from some published version
- Allowed for admin users
- Not allowed if there is an existing draft version. It should be removed first (see https://github.com/VRK-YTI/yti-datamodel-api/pull/335).

YTI-4251 create draft

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/IndexService.java

- use correct method for reindexing external resources
- check that external namespace ends with resource separator (`/` or `#`). From some graphs resource separator is missing because with that it wont't resolve.

YTI-4257 fix external resource reindexing

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/IndexService.java

Remove external resource index from index config map passed to the initilize method. If passed, it will be recreated and external resources are indexed on startup only if index is created for the [first time](https://github.com/VRK-YTI/yti-datamodel-api/blob/1e070466ac7a41c869d7281e9f612edd1d3a0fa1/src/main/java/fi/vm/yti/datamodel/api/v2/service/IndexService.java#L95)

YTI-4257 skip initializing external resource index on startup

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java

Class may have a reference to itself in one of the resources. Allow removing the class, since that reference is going away anyway.

Allow removing class with references to itself

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/health/FusekiHealthChecker.java
src/main/java/fi/vm/yti/datamodel/api/v2/health/OpenSearchHealthChecker.java
src/main/resources/config/application.properties.template

This will allow having readiness probes in kubernetes to stop traffic if the backend services are down.

add custom health checks for fuseki/opensearch connection

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ResourceNotFoundException.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/release/ReferencesExistsValidator.java

Use `ResourceNotFoundException` from common library. Otherwise only generic error message is displayed. Remove the exception class from datamodel-api project
Fixed also data model validation to handle orphan blank nodes.

YTI-4356 fix concept resolve error
