VRK-YTI/yti-datamodel-api

src/main/java/fi/vm/yti/datamodel/api/service/TermedTerminologyManager.java

Added type for ConceptSchemes

---

src/main/java/fi/vm/yti/datamodel/api/service/GraphManager.java

Merge to master after testing in development

Added recursive delete for #PositionGraph properties

---

src/main/java/fi/vm/yti/datamodel/api/service/XMLSchemaWriter.java
src/main/java/fi/vm/yti/datamodel/api/utils/XMLSchemaBuilder.java

Refactored creating xml for resource and model

Xml export fix

---

src/main/java/fi/vm/yti/datamodel/api/index/FrameManager.java
src/main/java/fi/vm/yti/datamodel/api/utils/LDHelper.java

Create a copy of the frame, because it is modified and thus the changes are affected other data models also

YTI-1461 fix property sorting

---

src/main/java/fi/vm/yti/datamodel/api/index/FrameManager.java

Try to reconstruct graph if model not found. Improve exception handling

Model not found handling

---

src/main/java/fi/vm/yti/datamodel/api/model/ReusableClass.java

Use label instead of classLabel in query to fix localization when making concept reference

YTI-1476 modify sparql query

---

src/main/java/fi/vm/yti/datamodel/api/model/ReusableClass.java

Reverts VRK-YTI/yti-datamodel-api#24

Revert "YTI-1476 modify sparql query"

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/model/Usage.java

When searching by resourceId or concept, allow specifying model as well to further limit the results
YTI-1517

allow modelIRI with other parameters in usage search

---

src/main/java/fi/vm/yti/datamodel/api/index/model/IndexModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/model/AbstractModel.java
src/main/resources/model_mapping.json

Add datamodel documentation to elasticsearch index

YTI-1475 datamodel documentation

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/config/AjpConfig.java
src/main/java/fi/vm/yti/datamodel/api/config/JerseyConfig.java

- Add context path /datamodel-api to expose actuator endpoint
- Create git.properties in the build

YTI-1474 enable actuator route

---

build.gradle

Use owasp version installed in jenkins agent

YTI-448 downgrade owasp plugin

---

src/main/java/fi/vm/yti/datamodel/api/model/SuomiCodeServer.java
src/main/resources/logback-spring.xml

* Add stacktrace to log pattern
* change log level to INFO and log exception

YTI-1565 improve codescheme integration logging

---

src/main/java/fi/vm/yti/datamodel/api/model/OPHCodeServer.java

Add caller-id header for accessing OPH's codelists

YTI-51 Add caller-id header

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/model/ModelCreator.java
src/main/java/fi/vm/yti/datamodel/api/endpoint/profile/ProfileCreator.java
src/main/java/fi/vm/yti/datamodel/api/index/SearchIndexManager.java
src/main/java/fi/vm/yti/datamodel/api/model/AbstractClass.java
src/main/java/fi/vm/yti/datamodel/api/model/AbstractModel.java
src/main/java/fi/vm/yti/datamodel/api/model/AbstractPredicate.java
src/main/java/fi/vm/yti/datamodel/api/model/ApplicationProfile.java
src/main/java/fi/vm/yti/datamodel/api/model/DataModel.java
src/main/java/fi/vm/yti/datamodel/api/security/AuthorizationManagerImpl.java
src/main/java/fi/vm/yti/datamodel/api/service/RHPOrganizationManager.java

* Add parent organization to sparql queries
* Parent organization members have access to child organization's content (add separate lists for editor organizations and organizations displayed in public view)

YTI-1592 Child organizations

---

build.gradle

YTI-1790 spring boot upgrade

---

src/main/java/fi/vm/yti/datamodel/api/model/SuomiCodeServer.java

Check if contentModified property exists before getting timestamp

YTI-2203 fix check modified timestamp

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/codes/CodeList.java
src/main/java/fi/vm/yti/datamodel/api/endpoint/codes/Codes.java
src/main/java/fi/vm/yti/datamodel/api/model/OPHCodeServer.java
src/main/java/fi/vm/yti/datamodel/api/model/SuomiCodeServer.java
src/main/java/fi/vm/yti/datamodel/api/service/CodeSchemeManager.java
src/main/java/fi/vm/yti/datamodel/api/service/JenaClient.java

Replace fetchDataSet method calls with sparql ASK query because of performance issues

YTI-2283 replace fetch data set

---

src/main/java/fi/vm/yti/datamodel/api/service/NamespaceManager.java

Added application/ld+json to namespace resolving. Needed for vocabularies that are only published as json-ld files.

Added JSON-LD content-type to namespace resolving

---

src/main/java/fi/vm/yti/datamodel/api/index/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/index/model/ModelSearchRequest.java
src/test/java/fi/vm/yti/datamodel/api/index/ModelQueryFactoryTest.java
src/test/resources/es/modelrequest.json

- Add search filters for organization, groups (isPartOf) and type (profile or library)
- Removed some unused constructors

YTI-2297 missing search filters

---

src/main/java/fi/vm/yti/datamodel/api/endpoint/genericapi/ResolveNamespace.java
src/main/java/fi/vm/yti/datamodel/api/service/NamespaceManager.java

- provide custom accept header for namespace resolving
- parse rdf from inputstream, because returned content-type might be unsupported

YTI-2286 Namespace resolving fixes

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java

Improvements for saving datamodel

YTI-2327 improve mapping and add tests

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/ElasticIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/elasticsearch/index/IndexModel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ApiError.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ApiValidationError.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ApiValidationErrorDetails.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidDatamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/main/resources/config/application.properties
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java

Changelog:
- Authorization check
- Organisation check through fuseki
- Service category check through fuseki
- ElasticSearch indexing
- Validation

YTI-2327: datamodel saving

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DCAP.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/MappingError.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexClass.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidClass.java
src/main/resources/class_v2_mapping.json
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchIndexerTest.java
src/test/resources/test_datamodel_with_class.ttl

Changelog:
- new ClassDTO for creating classes
- Moved DCAP to a 'property' class
- Class controller and mapper for adding classes to data models
- Validation for classDTO
- Indexing for opensearch
- Unit tests

New class controller

---

src/main/java/fi/vm/yti/datamodel/api/config/AjpConfig.java
src/main/java/fi/vm/yti/datamodel/api/config/OpenSearchConfig.java
src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/BaseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/OrganizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchUtil.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexBase.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/FrontendService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java

Sonar errors

---

src/main/java/fi/vm/yti/datamodel/api/config/RestConfig.java
src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/error/ApiGenericError.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaQueryException.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java

Changelog: 
- Fixed language query for indexing, it was trying to read old datamodels languages wronly
- Counts query only takes from models
- Remove extra null check from mapperutils
- Fixed more sonarqube issues

YTI-2436: Fixed language query for indexing

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/ModelSearchRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ClassQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ClassQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ModelQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/OpenSearchIndexerTest.java
src/test/resources/es/classRequest.json
src/test/resources/es/modelrequest.json

Changelog:
- Model searching added
- ClassQuery to use util functions
- UUID instead of String
- Add incomplete model/class query
- reordered search index service

YTI-2434: Added model searching for frontend page

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceType.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/JenaService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidResource.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/NamespaceResolveControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- Resource controller for adding both attributes and associations
- renamed some jenaservice functions to reflect on what they do 
- class update was missing put to database
- better tests for class controller
- add resourcerelationship moved to util class
- removed some unused imports
- prepared code for update and indexing

YTI-2481: Added attributes to datamodel

---

src/main/java/fi/vm/yti/datamodel/api/config/RestConfig.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/TerminologyServiceTest.java

Create own http client with configuration for uri resolving and groupmanagement. Remove old configurations (e.g. RestTemplate)

YTI-2371 http client refactor

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- Changed update endpoint to actually update
- resource mapper added update resource method
- Fixed slight mistake in class update, should update class modified instead of model modified.
- tests

YTI-2490: update resources from endpoint.

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/TerminologyMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/TerminologyServiceTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Changelog:
- Mappers to static
- Static mocks
- Sonarqube issues

YTI-2486: mappers to static

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java

Changelog:
- Changed to Info DTO for classes
- Info dto has extra fields of
-  created
- modified
-  uri
- contributor
-  contact
- added uri field to resource as well
- made some minor code style fixes
- unit tests to reflect this change

YTI-2505: more info fields to class and resource dto

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoBaseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/UserDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/resources/models/test_datamodel_with_resources.ttl
src/test/resources/test_datamodel.ttl

- created base class for holding creator / modifier information
- save user's id for all resources when saved or modified
- capability for user name mapping (this will be implemented later)

YTI-2500 Save user and modifier id

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog: 
- Get as file endpoint
- Currently limited to json-ld, turtle and rdf
- test for endpoint
-removed debugging andDo print

YTI-2530: GET as file endpoint

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/resources/test_datamodel.ttl

Changelog:
Added contact field for datamodel
Cleaned up modelMapper a bit
test for contact
validation for contact

YTI-2507: Added contact field for datamodel

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

Skip resolving concept if blank. Better validation will be implemented in different task

YTI-2506 check if concept is blank

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationAssociationDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationAttributeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/VisualizationClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java
src/test/resources/models/test_datamodel_visualization.ttl

- Separate attribute and association to own dto classes
- Some refactoring in mapping logic

YTI-2544 add attributes and associations to visualization data

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveControllerTest.java

Redirections per resource's type:
class -> /model/prefix/class/classID
attribute -> /model/prefix/attribute/attributeID
association -> /model/prefix/association/associationID

YTI-2497 add resource specific paths for site redirection

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/TerminologyServiceTest.java

Quick fix for adding concept to the resource. Need to decide in which format URIs need to be saved in fuseki, see ticket YTI-2584

add terminology suffix to uri

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/NodeShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceInfoBaseDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimplePropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

add separate resource dtos for class and nodeshape

YTI-2591 map property shapes to dto

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java

Changelog:
- Initialize codelist always so no null error can happen

YTI-2606: Fix codelist null error

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Datamodel.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- Created endpoints for free identifier check in ResourceController and ClassController
- Merged identifier and prefix check into one function
- Added resource identifier max length limit of 32
- Refactored some validator functions

YTI-2632: Created endpoints for checking free identifier check

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/IndexModel.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DatamodelTest.java
src/test/resources/test_datamodel_library.ttl

Changelog:
- Added language versioned documentation field
- Removed documentation field from indexmodel (this is likely never needed when searching datamodels)
- Moved around some modelMapper lines for code clarity

YTI-2510: Added documentation field

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassControllerTest.java

- Check that none of values in the label map is not null or blank
- Change status validation that it's always mandatory. Not only in creation
- Add validation for subject

YTI-2425 Validation fixes and improvements

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

See https://github.com/VRK-YTI/yti-terminology-api/pull/122

YTI-2584: Removed terminology suffix when getting concept

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java

- skip removing external namespace prefixes while editing
- add prefixes to exported model

YTI-2638 namespace handle prefixes

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ResourceValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidResource.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

- Validation for attributes range as one of the possible range values
- Separation of attribute and association endpoints
- More unit tests

YTI-2666: Validation for attributes range

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V3_ApplicationProfileType.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V4_ApplicationProfileType.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl
src/test/resources/models/test_datamodel_with_minimal_resources.ttl
src/test/resources/test_datamodel_profile.ttl
src/test/resources/test_datamodel_v1.ttl

- add custom type `iow:ApplicationProfile` for application profiles in addition to owl:Ontology
- refactor checking model type
- migration script for changing existing profiles' types

YTI-2617 application profile type

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Create and update endpoint for resource now more similar

YTI-2666: Change endpoint name for create and update

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/dto/CountRequest.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/CountQueryFactoryTest.java
src/test/resources/es/models_count_request.json

Changelog:
- Filtering options for count query to accurately count datamodels when filtering

YTI-2586: Added filtering options to count query

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java

Changelog:
use the following flag to enable default namespace resolution in application.properties
`namespaces.resolveDefault=true`

YTI-2660: add flag for resolving external namespaces.

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java

Changelog:
- Fix application profile check
- Fix faulty unit test with wrong uri

YTI-2637: Fix application profile check

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/Iow.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

Changelog:
- new fields and unit tests

YTI-2678: new fields for attribute restriction

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/NodeShapeValidator.java

Related to https://github.com/VRK-YTI/yti-datamodel-api/pull/164
Forgot to push changes for validation

YTI-2693 validation rule for visualization

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimplePropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java

Changelog:
- Add fromShNode property
- Change how identifier is gotten for propertyshape

YTI-2687: Add info if propertyshape is from sh:node

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java

Changelog:
- Accidentally getting schemes from wrong repo

YTI-2696: Fix datamodel get

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V1_Initial.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V2_Separator.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V3_ImportsRequires.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V4_ApplicationProfileType.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FakeableUserController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/NamespaceResolveController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResolveController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/annotation/ResourceNotFound.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ExceptionHandlerAdvice.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/IndexControllerTest.java

Changelog:
- New swagger documentation
- Fixed some minor sonarqube issues

YTI-2710 swagger documentation

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/LinkDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/resources/test_datamodel_library.ttl

Changelog:
- Link DTO for datamodel
- uri and name are required, description optional
- UNIT tests

YTI-2722: Added links field for datamodels

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/AssociationRestriction.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/AttributeRestriction.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidPropertyShape.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

Changelog:
- Changed property shape to have 2 endpoints just like resource
- Moved some functions so that it works with the 2 new DTO files
- Unit tests

YTI-2709 property shape split

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/AttributeRestriction.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceControllerTest.java
src/test/resources/models/test_datamodel_profile_with_resources.ttl

Changelog:
- Add codelist to attribute restriction

YTI-2731: add codelist to attribute restriction

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/AttributeRestriction.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/PropertyShapeInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java

Changelog:
- Add sh:pattern and sh:languageIn properties

YTI-2746: Add sh:pattern and sh:languageIn properties

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ClassInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java

Changelog:
- Added new field disjoint with
- Unified some class/resource methods

YTI-2729: Disjoint with class

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimpleResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java

Changelog:
- Added more fields to simpleresourcedto

YTI-2727: Add more about classes and its resources

---

src/main/java/fi/vm/yti/datamodel/api/StartUpListener.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/OrganizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/OrganizationMapperTest.java

Changelog:
- Added group management synchronization
- Only updates if changed

YTI-2495: Group management Sync

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/ClassValidator.java

Changelog:
- Validation for disjointwith
- Made class validation more common

YTI-2729: Added validation for disjointwith

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/CodeListService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java

Changelog:
- Resolve codelists when adding or updating resource
- Add to datamodel if not added adding to resource

YTI-2684: codelist allow unlinked

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java

- fix checking if organization does not exist
- return empty list instead of exception

fix checking child organizations

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/NodeShapeMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java

Changelog:
- Allow toggle of external properties

YTI-2726: allow toggle of external properties

---

src/main/java/fi/vm/yti/datamodel/api/v2/repository/CoreRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/GroupManagementService.java

Changelog:
- Invalidate organization cache if there are changes
-Change sync time from 5 min to 30 min

YTI-2884: Org cache invalidation

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/DataModelInfoDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/InternalNamespaceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/resources/test_datamodel_internal_reference.ttl

Changelog: 
- Added better info of internal namespaces
- Fixed disjointWith in another ticket.
- Removed some duped code
- Slightly more unit testing

YTI-2999: added better info of internal namespaces

---

src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidationConstants.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java

Changes in this PR:
- Increased prefix maximum length to 32 from 10

Increased prefix max length to 32

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/CodeListService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java

Changelog: Added more verbose resolution logs

YTI-2758: Made terminology and codelist resolution more verbose

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/UriDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java

If uri referred resource has label (e.g. rdfs:subClassOf, rdfs:domain) add label to URIDTO object

YTI-3038 Add labels to uris

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/CountQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/CountQueryFactoryTest.java

Changelog:
- Update count query to work with new status changes and other query improvements

YTI-3198: Fix count query to show correct amount of datamodels

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java

Changelog:
- Only save visualisation data if its saved on draft version

YTI-3194: Save visualisation for version conditionally

---

src/main/resources/config/application.properties

Need to increase memory limit for fetching large terminologies

YTI-3125 increase memory limit for web client

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V5_VersionStatus.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V6_VersionStatusResources.java
src/main/java/fi/vm/yti/datamodel/api/migration/task/V7_VersionDraft.java

Changelog: 
- Suppress Class name not following conventions warnings
- Make unversioned a draft and create a new release for suggested versions

YTI-3308:Create draft versions and releases

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelVersionInfo.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/SemVer.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/utils/SemVerTest.java
src/test/resources/models/test_datamodel_prior_versions.ttl

Changelog:
- Get version history DTOs from endpoint
- Unit tests

YTI-3200: get version history

---

src/main/java/fi/vm/yti/datamodel/api/v2/repository/ConceptRepository.java
src/main/java/fi/vm/yti/datamodel/api/v2/repository/SchemesRepository.java

Changelog:
add update endpoint to concept and scheme repositories

YTI-3319: Fix migration not initializing

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ResourceServiceTest.java

- Endpoints for renaming classes, attributes and associations
- Service for handling renaming. Use Jena's ResourceUtils functionality, which handles all references as well

YTI-3328 rename resources

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/PropertyShapeMapperTest.java

- Add terminology reference while adding concept
- Add model reference also while editing
- Fix bug adding range for attribute (no need to be added as references)

YTI-3406 missing functionalities adding references

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java

include drafts to search if they are owned by user's organization

Fix resource search

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java

Changelog:
- Change dto Sets to not be null
- This was also against how our endpoint was supposed to work (delete value if nothing is given)
- Fix the unit tests with this

YTI-3205: Fix null error in cyclical check

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ResourceQueryFactory.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
src/test/resources/es/classRequest.json

Fix intersection logic
Status filter moved to datamodel

YTI-3555: Status filter moved to datamodel

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtilsTest.java

Changelog:
- Rename visualization resource during rename of resource
- Unit test

YTI-3597: Rename visualization resource

---

src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ExternalNamespaceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/LinkDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/BaseValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/DataModelValidator.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/migration/V1DataMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/resources/models/test_datamodel_library_version.ttl
src/test/resources/test_datamodel_library.ttl

Localize link's name, description and external namespace's name

YTI-3372 missing localizations

---

src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ClassController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ResourceController.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/SemanticVersionValidator.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/ValidSemanticVersion.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/DataModelControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java

Changelog:
- Allow deletion of versioned model if superuser
- Allow deletion of DRAFT model if superuser
- Delete resources from index when deleting datamodel 
- Semantic version validation on parameters

YTI-3567: Delete versioned model if superuser,

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ResourceService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java

Changelog;
- New base resource service
- Move common function to base resource service
- Fix some unit tests that broke because of this
- Some functions could not be mocked anymore

YTI-3480: refactor common service functions into one.

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/ClassServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java

When creating new class, save a position with y coordinate 50 less than existing minimum y coordinate

YTI-3615 add default position for created class

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/VisualizationDataMapperTest.java
src/test/resources/models/test_datamodel_library_visualization.ttl
src/test/resources/models/test_datamodel_library_with_resources.ttl

- Show range's / data type's curie in visualization
- Updated test data

YTI-3574 fix datatypes in visualization

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java

This fixes bug where all models were shown

YTI-3666: Trim query string

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/visualization/VisualizationItemDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java

Needed for https://github.com/VRK-YTI/yti-terminology-ui/pull/604
Adds uri to most visualization item.

YTI-3647: added uri to visualization

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationController.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/VisualizationControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java

Changes in this PR:
- Support for saving positions for versioned data models added

Yti 3660 versioned visualization save

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelURI.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ResourceMapperTest.java
src/test/resources/models/test_datamodel_library_with_resources.ttl
src/test/resources/test_datamodel_library.ttl

- Add version to URI if link's target is in the same model and the model is not draft
- Fixed test data

YTI-3659 fix links to the resources of the same model

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V11_FixConceptAndCodeListStatus.java
src/main/java/fi/vm/yti/datamodel/api/security/AuthorizationManagerImpl.java

- Migration script to change http://uri.suomi.fi/datamodel/ns -> https://iri.suomi.fi/model in concept and schemes repositories
- Fix bug checking user privileges

YTI-3157 fix status and type in concept and schemes repository

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/CodeListMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/MapperUtils.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java

Changelog:
- Make sure everything makes uris instead of string when setting publicationStatus property

YTI-3720: publicationStatus update use uri

---

src/main/java/fi/vm/yti/datamodel/api/migration/DataMigrationController.java

Modify migration endpoint to accept several comma separated prefixes

YTI-3688 migrate several prefixes at once

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java

- Use graph uri in prefix mapping
- Fix logic fetching external resource with version

YTI-3753 fixes for prefix mapping and fetching single resource

---

README.md
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java

- Fix adding prefixes to versioned model (use uri without version)
- Fix migrating restrictions' range
- Add troubleshooting section to README

Migration fixes and update readme

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java

Add node ids to list to prevent the same node being handled more than once. This is mandatory for scenario with multiple associations with the same domain and range

YTI-3747 fix scenario for multiple associations with the same domain and range

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java

In initial implementation, the search would always search for resources with an empty string, and come up with a list of models that had any resources in them. This list would then be added as a "must" expression to opensearch, limiting the main search too much.
Now matching resources will only be searched if a query string was set.

only search within resources if a query string was set

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/VisualizationServiceTest.java

- Sort visualization data by resources finnish label (or english if finnish not present)
- Fix index not found error by creating external_v2 index on startup if not exist

YTI-3841 resource sorting

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java

Remove existing namespace resources from the model before adding new ones.

YTI-3572 Handle external namespaces 

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/SimplePropertyShapeDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java

Map curie for property shape and note for external resource, related to frontend changes https://github.com/VRK-YTI/yti-ui/pull/686

YTI-3808 Simple resource mapping changes

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelUtils.java

- Fix determining resource's type
- When handling versioned URIs, skip external resources

YTI-3808 fix external resource view

---

src/main/java/fi/vm/yti/datamodel/api/config/SpringAsyncConfig.java
src/main/java/fi/vm/yti/datamodel/api/index/OpenSearchConnector.java
src/main/java/fi/vm/yti/datamodel/api/migration/DataMigrationController.java
src/main/java/fi/vm/yti/datamodel/api/migration/SpringAsyncConfig.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMapper.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java
src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/index/OpenSearchIndexer.java

- Execute migration asynchronously 
- Add some missing namespaces to models
- Fix renaming library resources (there might be more than two duplicate identifiers in the model)
- Add missing languages and tweak setting default name for the model
- Change some loggings to debug level in indexing

YTI-3881 Migration improvements

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/ModelQueryFactory.java
src/test/resources/es/modelrequest.json

Fix the structure of the query. Add draft exclusion query separetely from label query. Use more descriptive variable names.

YTI-3893 Fix model query

---

src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMapper.java
src/main/java/fi/vm/yti/datamodel/api/migration/V1DataMigrationService.java

Add rootResource (UI: juurisolmu) and absolutePath (UI: API-polku) properties to migration

YTI-3881 custom properties for resources

---

src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/OpenAPIBuilder.java
src/test/java/fi/vm/yti/datamodel/api/index/OpenSearchUtils.java
src/test/java/fi/vm/yti/datamodel/api/mapper/MapperTestUtils.java
src/test/java/fi/vm/yti/datamodel/api/v2/endpoint/ExportControllerTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/CountQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ModelQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/OpenAPITest.java
src/test/resources/open-api-data.ttl
src/test/resources/open-api-expected.json

Build open api document using swagger's domain classes.
Refactor: move `OpenSearchUtils#getJsonString` method to MapperTestUtils class

YTI-3958 Open API support

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/BaseResourceService.java

Use getReferences query to determine if there are references to the resource being removed. List references (first 10) in the error message.

YTI-4030 Improve checking references before delete resource

---

.gitignore
build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/SubscriptionDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/SubscribeController.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/DataModelSubscriptionService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/sns/MockSnsService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/sns/SnsService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/sns/SubscriptionService.java
src/main/resources/logback-spring.xml
src/main/resources/release-notification-template.html
src/test/java/fi/vm/yti/datamodel/api/v2/service/DataModelServiceTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/SubscriptionServiceTest.java

- Created controller and service for handling subscriptions
- Created separate service for interactiong AWS SNS with mock implementation
- Send notification after data model has been published

YTI-3623 Notifications

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ModelMapper.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ModelMapperTest.java

Add child organization's parent as a contributor too if not already exists.

YTI-4087 Handle adding child organization as a contributor

---

src/main/java/fi/vm/yti/datamodel/api/migration/task/V15_VisualizationAddOrigin.java

- add hasNext check for iterator (most likely caused problem only in dev environment because of broken visualization data)
- fix postition resource base uri (must not include version)

YTI-4025 Visualization migration fixes

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/VisualizationMapper.java

Without this check corners cannot be added between class node and attribute (with rdfs:domain) node

YTI-4025 handle hidden nodes between class node and attribute node

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/FrontendService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/OrganizationMapperTest.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/FrontendServiceTest.java
src/test/resources/organizations.ttl

Use lower case label in sorting

YTI-4091 Fix organizations sorting

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/VisualizationService.java

- Filter external resources by id, not URI because id contains version info
- Create external class for association references

YTI-4164 Fix external resources in visualization

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaBuilder.java
src/test/java/fi/vm/yti/datamodel/api/v2/service/JSONSchemaTest.java
src/test/resources/json-schema-expected.json

- Fix NullPointerException when handling association ref
- Fix handling max- and minCount
- Fix a couple sonar lint issues

YTI-4184 JSON schema fixes

---

build.gradle
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ExternalClassDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/dto/ExternalResourceDTO.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ResourceMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/ClassService.java
src/main/java/fi/vm/yti/datamodel/api/v2/service/NamespaceService.java
src/test/java/fi/vm/yti/datamodel/api/mapper/ClassMapperTest.java

- Simplify query for fetching external resource's attributes and associations
- Fix type mapping for external resource and map description
- Add prefixes to the model when fetching resources, so curie will display correct in the UI

YTI-4120 fetch external resource properties

---

src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/datamodel/api/v2/validator/PropertyShapeValidator.java

Add some extra datatypes for application profile. Return datatypes in alphabetical order.

YTI-4221 add more datatypes for application profile

---

src/main/java/fi/vm/yti/datamodel/api/v2/opensearch/queries/QueryFactoryUtils.java
src/test/java/fi/vm/yti/datamodel/api/v2/opensearch/ResourceQueryFactoryTest.java
src/test/resources/es/classRequest.json
src/test/resources/es/modelrequest.json

Check if there are spaces in the search query. If there search for an exact phrase. In case of singe word, prioritize exact match.

YTI-4278 search improvement

---

src/main/java/fi/vm/yti/datamodel/api/v2/mapper/ClassMapper.java
src/main/java/fi/vm/yti/datamodel/api/v2/utils/DataModelURI.java

Remove todo comments and revert checking attribute's range when added to the class

YTI-3749 remove todo comments

---

src/main/java/fi/vm/yti/datamodel/api/v2/service/IndexService.java

Add sort key for labels in index mappings

Fix search result sorting
